# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d2367daaa84f66f3a2fd5ef182ac38e2fe80edc33727de6e940151a8c1e98aaa4471925780d9736444fbdd71df4411c7420bcf9cfa933d5710a426d0c2e3d5e8

test:
  secret_key_base: 0dcd267de0675a5a182fe33f6e06fe72c7ccfd8f904ddd147695917039ff779d7bd95657cbff02c509c8739b90ae1957f66b9fc2e0339c064bddcb542a41a408

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
